### ISSUE TITLE
standalone does not work (under relative path)

### ISSUE THREAD

**Issue by JensLincke** [LivelyKernel/lively.modules#1]
we checked out and installed this package (npm install) 
and hosted its files statically under:

https://lively-kernel.org/lively4/lively.modules/examples/browser-standalone/index.html

This pages seems to fail, because the System.js configuration is not suited for this case?

How can we load lively-modules standalone or with a running System.js installation in Lively4?

**Comment by rksm** [comment]
I've updated the code in github of the various packages, the example should work now, see e.g.
  https://dev.lively-web.org/node_modules/lively.modules/examples/browser-standalone/index.html

(note that you of course have to change the path for loading SystemJS and the load script in the html file)

I've not updated npm yet and to install all relevant packages you will need to run this script for now:
  https://gist.github.com/rksm/e4a62b0161f3f26311342ac65c437717
(You can leave out LivelyKernel if you just want lively.modules)

Apart from that I will starting to deploy a transition Lively install including the tools we are building on
  https://dev.lively-web.org

The module browser can be tested at
  https://dev.lively-web.org/module-browser.html

**Comment by JensLincke** [comment]
works with manual running of dev installation script now

**Comment by rksm** [comment]
I have added a ready-to-go loader `dist/lively.modules.js`. Please see the updated examples in [examples/browser](../tree/master/examples/browser) and [examples/nodejs](../tree/master/examples/nodejs) for the usage. This should make it straightforward.
