### ISSUE TITLE
persistent module state

### ISSUE THREAD

**Issue by onsetsu** [LivelyKernel/lively.modules#10]
How can a module keep and manage its own state persistently while being updated and reloaded. 

Example: lively4's components module needs to keep track of its templates and prototypes...

**Comment by rksm** [comment]
First of all, most of the time you don't need to reload the module at all. Use [`moduleSourceChange(moduleName, newSource, options)`](https://github.com/LivelyKernel/lively.modules#modulesourcechangemodulename-newsource-options) to modify a module, this will update the internal module state + update existing exports.

Now there is one special case: Adding a new export. In the future this will not be an exception but for now a module reload is indeed necessary. Use [`reloadModule(moduleName, options)`](https://github.com/LivelyKernel/lively.modules#reloadmodulemodulename-options) to reload the module and its dependency tree. As you can see the options takes two fields: `{reloadDeps: BOOL, resetEnv: BOOL}`. If you set `resetEnv` to false, the previous module state will be persistently used. One place where we use it is in [lively.modules/index.js](https://github.com/LivelyKernel/lively.modules/blob/master/index.js#L235) where we hold on to the internal state of the `defaultSystem` var, even if we reload that module.

**Comment by rksm** [comment]
The newest release improved the way how modules are updated. When using `moduleSourceChange` or `runEval` the module object (= exports) is now always update:
- changed exports are propagated recursively to dependent modules via module bindings
- new exports are added(!) to the existing module object. This is only done when the module object isn't frozen. By default we now prevent freezing modules. If you decide you want frozen modules you will need to do a reload in those cases.
- different to what we did before we do _not_ re-run dependent modules on source changes or eval, i.e. if you have a computed value that depends on an import it won't be updated automatically (the imports are always up-to-date, though)
