### ISSUE TITLE
imported modules are not updated in workspace modules

### ISSUE THREAD

**Issue by onsetsu** [LivelyKernel/lively.modules#11]
Contents of workspace:

```
import foo from "foo.js"
foo.bar()
```

After changing the `bar` in "foo.js" and reloading it, the workspace still executes the old `bar` method. 
Did we use the wrong method to update a module? We currently use `lively.modules.reloadModule(urlToFooJS);`.

**Comment by rksm** [comment]
When I remember correctly you use a hack to make your workspaces into modules. Each module is expected to have it's unique id, I think you currently use something like "lively://". This makes it impossible for the workspace as a dependency of foo.js.

**Comment by rksm** [comment]
@onsetsu Solved?
