### ISSUE TITLE
Including lively modules bundle as test dependency

### ISSUE THREAD

**Issue by onsetsu** [LivelyKernel/lively.modules#14]
When importing the lively.modules bundle `lively.modules-with-lively.vm.js` as dependency, we get the following error, because acorn is undefined.

```
Chrome 51.0.2704 (Windows 10 0.0.0) ERROR
  Uncaught TypeError: Cannot read property 'plugins' of undefined
  at http://localhost:9876/src/external/lively.modules-with-lively.vm.js:10705
```

(We include the bundle via script tag for testing)

**Comment by rksm** [comment]
The [lively-system-examples](https://github.com/LivelyKernel/lively-system-examples) repo has setups to various combinations such as [browser/index.html](https://github.com/LivelyKernel/lively-system-examples/blob/master/browser/index.html). Can you check if you have included babel + systemjs?
