### ISSUE TITLE
System notifier for module and package events

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.modules#22]
As @levjj pointed out in #20 we need a notification mechanism for changes of the module, package, and System state. Main use for the notifications would be tools that depend on lively.modules, e.g. when having multiple browsers open, one browser changes the definition of a module then the other browsers (might) need to update their views.

[notify.js](https://github.com/LivelyKernel/lively.modules/blob/master/src/notify.js) has a first implementation of a notification system currently this is only used for module changes [change.js](https://github.com/LivelyKernel/lively.modules/blob/master/src/change.js#L20).

Let's make a list of use cases from which we can deduct what functionality the notifier needs to include.
1. What kinds of events do we need? notifying about doits, module (un)loads, package loads, ...?
2. What would a good interface to the notifier look like? How can notifications be submitted, how can dependents subscribe? There is currently a custom (un)subscribe mechanism which has the advantage of using ids for listeners so duplicated subscriptions can easily be avoided. Alternatively we could switch to nodejs-like event handlers that are available to us cross-platform via [lively.lang/events.js](https://github.com/LivelyKernel/lively.lang/blob/master/doc/events.md#events).

Opinions?

/cc @tylervernonsmith @merryman

**Comment by levjj** [comment]
I'm currently using subscriptions via `notify.js` and that seems to work fine for a local system, so maybe we don't have to change that much.

I think the most important events would be
- module/package created (the associated file/resource was not present before)
- module/package loaded
- module/package changed
- module/package unloaded
- module/package removed (the associated file/resource is not present anymore)

I also like the idea of just using one lively.lang/events.js event-emitter per "system". There could be multiple systems (local and remote) but each should allow the same operations and subscriptions.

One more thing: It would be great if subscriptions were weak references. So, if the subscribing object becomes garbage, it can be collected and the subscriptions removed. JavaScript has WeakMap and WeakSet but I don't think we can use these to make subscriptions weak.
