### ISSUE TITLE
Improving compile performance

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.modules#36]
Compilation time of modules takes way too long, more than 30-45secs for a bootstrapped lively.morphic.

A first step to address that was added in commit 5406707d572422a640ef300cffd3f22044ba540e that introduced an IndexDB-based cache for module translation when lively.modules is used browser side. Loading lively.morphic fully cached now takes ~4secs.

We plan to improve that further by adding a customized transpiler to SystemJS (instead of "plugin-babel"). An example of the setup:

``` js
import * as babel from "https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.17.0/babel.js";

var myTranspiler = {
  translate: function(load, traceOpts) {
    console.log(`translating ${load.name} [${load.metadata.format}]`);
    load.metadata.format = 'register';
    return babel.transform(load.source, {plugins: ["transform-es2015-modules-systemjs"]}).code
  }
}

System.set("my-transpiler", System.newModule(myTranspiler))
System.config({transpiler: "my-transpiler"})
```

By using either completely our own lively.ast-based translator or using a customized babel that only adds compilation steps required by the platform (feature detection) we should be able to improve compilation speed further.

**Comment by levjj** [comment]
FYI: Support for async/await is now enabled by default starting with Chrome 55:

https://www.chromestatus.com/feature/5643236399906816

Apart from our own rewriting, there should be almost no transpilation required anymore.

**Comment by rksm** [comment]
Yes, we hope to make use of this fact by using feature detection for configuring the compiler. Still, we have to support browsers like Safari that not even have arrow functions, though.

**Comment by rksm** [comment]
457ad31c0dd7a995ece6f109bb8fe5c950396858 adds support for this.

Due to various issues older platforms still need the full magic of SystemJS' plugin-babel so I left support for this in for now. On modern platforms only a lightweight source transform will be applied.
